from typing import Dict, Any, List

import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder


class CaseOutcomeModelService:
    def __init__(self, dataset_path: str):
        self.dataset_path = dataset_path
        self.model = None
        self.label_classes: List[str] = []

    def train(self):
        df = pd.read_csv(self.dataset_path)

        feature_cols = [
            "case_type",
            "ipc_section",
            "evidence_strength",
            "past_criminal_record",
            "severity",
            "victim_impact",
        ]
        target_col = "outcome"

        X = df[feature_cols]
        y = df[target_col]

        preprocessor = ColumnTransformer(
            transformers=[
                (
                    "cat",
                    OneHotEncoder(handle_unknown="ignore"),
                    feature_cols,
                )
            ]
        )

        clf = RandomForestClassifier(
            n_estimators=220,
            random_state=42,
            min_samples_leaf=1,
        )

        self.model = Pipeline(
            steps=[
                ("preprocessor", preprocessor),
                ("classifier", clf),
            ]
        )
        self.model.fit(X, y)
        self.label_classes = list(self.model.named_steps["classifier"].classes_)

    def predict(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        if self.model is None:
            self.train()

        evidence_strength = payload.get("evidence_strength", "Moderate")
        past_record = payload.get("past_record", "None")

        severity = "Medium"
        case_facts = payload.get("case_facts_summary", "")
        if "injury" in case_facts.lower() or "fatal" in case_facts.lower():
            severity = "High"

        victim_impact = "Moderate"
        if evidence_strength == "Strong":
            victim_impact = "Severe"
        elif evidence_strength == "Weak":
            victim_impact = "Low"

        record = {
            "case_type": payload.get("case_type", "Criminal") or "Criminal",
            "ipc_section": payload.get("ipc_section", "") or "",
            "evidence_strength": evidence_strength,
            "past_criminal_record": past_record,
            "severity": severity,
            "victim_impact": victim_impact,
        }

        frame = pd.DataFrame([record])
        probs = self.model.predict_proba(frame)[0]
        classifier = self.model.named_steps["classifier"]
        feature_names = self.model.named_steps["preprocessor"].get_feature_names_out()
        importances = classifier.feature_importances_

        ranked_features = sorted(
            zip(feature_names, importances),
            key=lambda item: item[1],
            reverse=True,
        )[:5]

        outcome_probs = [
            {"label": label, "probability": round(float(prob) * 100, 2)}
            for label, prob in zip(self.label_classes, probs)
        ]
        outcome_probs.sort(key=lambda item: item["probability"], reverse=True)

        best = outcome_probs[0]
        confidence = "High" if best["probability"] >= 70 else "Medium" if best["probability"] >= 45 else "Low"

        return {
            "possible_outcome": {
                "probability": f"{best['probability']}%",
                "result": best["label"],
                "basis": "RandomForestClassifier trained on historical educational case dataset",
            },
            "confidence": confidence,
            "outcome_distribution": outcome_probs,
            "key_factors": [
                f"Evidence strength: {evidence_strength}",
                f"Past criminal record: {past_record}",
                f"Derived severity: {severity}",
                f"Derived victim impact: {victim_impact}",
            ],
            "feature_importance": [
                {"feature": name, "importance": round(float(weight), 6)}
                for name, weight in ranked_features
            ],
            "ai_reasoning": (
                "Prediction is generated by an ML classifier over structured legal features. "
                "Strong evidence and severe impact typically increase conviction likelihood in this dataset."
            ),
            "next_steps": [
                "Review evidentiary gaps with a legal expert",
                "Cross-check applicable IPC/CrPC provisions",
                "Prepare chronology and supporting documentation",
            ],
            "disclaimer": "This model is educational and not a substitute for legal advice.",
        }
